### ISSUE TITLE
Create a selenium portion of the app

### ISSUE THREAD

**Issue by G-Sivley** [G-Sivley/wordle-bot#10]
Create an instance of selenium that can go to the wordle website. This will be the start of allowing our app to solve the puzzle.

Implementation:
- create selenium_bot.py 
- init selenium
- have selenium go to wordle website

This would be a good start to add more features in the future!

Please feel free to contribute if you like, this is a very friendly environment!

**Comment by sazzad03** [comment]
Hi @G-Sivley, I am working on this issue

**Comment by G-Sivley** [comment]
Great! Thank you! Let me know if you have any questions.
