### ISSUE TITLE
Make "Word" class

### ISSUE THREAD

**Issue by G-Sivley** [G-Sivley/wordle-bot#3]
We need a class that can accept and assess words.

In this class, we need functionality that 
- initializes with a 5 letter word
- Separates the letters by position in the word
- Has the ability to assign, "green", "yellow", or "no color" to the letter

This is a great first issue for anyone that wants to help

**Comment by G-Sivley** [comment]
this class should go under a new file under app/word.py

If anyone has any questions, please let me know and I am happy to help!

**Comment by vedik2002** [comment]
@G-Sivley  do we have to take input of 5 letter words in the function in the class.

**Comment by G-Sivley** [comment]
Yes in the `def __init__(self):` function of the class.

Possibly receive the word and the the color (ie. clear, yellow, green)
