### ISSUE TITLE
Create a "remove_lines_with_words_in_index

### ISSUE THREAD

**Issue by G-Sivley** [G-Sivley/wordle-bot#4]
We need to iterate through the possible answers list. When we receive a yellow letter, we will want to remove the possible answers with the same letter in that position

For example: 
A: yellow in position 1

Abort: remove
Calcu: keep because a is in 2nd position.

This should be a method in the DataManipulator class

**Comment by YashxAnand** [comment]
Hi @G-Sivley , I would like work on this issue.

**Comment by G-Sivley** [comment]
@YashxAnand go for it! Let me know if you have any questions I can help you with.

**Comment by YashxAnand** [comment]
@G-Sivley I've a question. Is this method meant to receive only yellow letters?

**Comment by G-Sivley** [comment]
In theory yes. I think it would make most sense for the function to accept;

1. A list of words
2. A letter
3. The position of letter

And return
1. A list of words that do not have the letter in the position provided.

Does that make sense? If you come up with a better way, feel free to explore!

**Comment by YashxAnand** [comment]
Can you clarify why should this method receive a list of words? Shouldn't it directly remove the words from remaining_possible_answers.txt?

**Comment by G-Sivley** [comment]
I wanted to remove a list of words because I would like to keep the function as separated as possible from the actual code. If you would like to do it a different different way there's no problem with me however I think it would make the most sense to pass the code into a function so that we can use it elsewhere if needed in the future.

**Comment by G-Sivley** [comment]
Also when a function is small, it is easier to test.

**Comment by YashxAnand** [comment]
Yeah, I agree.
