### ISSUE TITLE
Create a "remove_lines_with_letters_not_in_index" function

### ISSUE THREAD

**Issue by G-Sivley** [G-Sivley/wordle-bot#5]
This is an similar to issue #4. 

This function should be created in the DataManipulator class. It should receive;
1. A list of words
2. A letter
3. The index of the letter

And return; 
1. A list of words that contain the letter at the specified index

This is for the green letter functionality to remove all words that don't have the green letter in the same position.

This is a great problem for new contributors! Let me know if you're working on it or if you have any questions!

**Comment by Vishwa-docs** [comment]
I am working on it
